language: python
python:
  - "2.7"
install:
  - "sudo apt-get update"
  - "sudo apt-get -y install build-essential clang-3.5 llvm"
  - "sudo ln -s /usr/bin/clang-3.5 /usr/bin/clang; sudo ln -s /usr/bin/clang++-3.5 /usr/bin/clang++"
  - "sudo apt-get -y install libffi-dev libssl-dev libxml2-dev libxslt1-dev libjpeg8-dev zlib1g-dev python-pip"
  - "sudo apt-get -y install libboost-all-dev"
  - "cd .. && git clone https://github.com/JohnLangford/vowpal_wabbit.git && cd vowpal_wabbit"
  - "make && sudo make install && cd .."
  - "cd vowpal_platypus && pip install -e ."
  - "pip install retrying"
  - "pip install git+https://github.com/uqfoundation/dill.git@master"
  - "pip install git+https://github.com/uqfoundation/pathos.git@master"
  - "cd .. && git clone https://github.com/peterhurford/vp_examples.git"
  - "cd vowpal_platypus"
script:
  - "python -m py.test"
  - "cd ../vp_examples && ./run_tests"
  # TODO: `pyflakes .; flake8 .` for code analysis
